name: Trivy Scan
description: Scan container image with Trivy
inputs:
  image:
    required: true
runs:
  using: "composite"
  steps:
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1  # v0.35.0
      with:
        image-ref: ${{ inputs.image }}
        format: "table"
        severity: "HIGH,CRITICAL"
