name: Trivy Scan
description: Scan container image with Trivy
inputs:
  image:
    required: true
runs:
  using: "composite"
  steps:
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@9f44c5c69c8f29909852ffb4058a52c57d20593d  # v0.35.0
      with:
        image-ref: ${{ inputs.image }}
        format: "table"
        severity: "HIGH,CRITICAL"
