apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: workload-variant-autoscaler
  namespace: workload-variant-autoscaler-monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: workload-variant-autoscaler
      control-plane: controller-manager
  namespaceSelector:
    matchNames:
    - workload-variant-autoscaler-system
  endpoints:
  - port: http
    scheme: http
    interval: 30s
    path: /metrics 