apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        - name: PROMETHEUS_TOKEN_PATH
          value: "/var/run/secrets/kubernetes.io/serviceaccount/token"
        - name: PROMETHEUS_CA_CERT_PATH
          value: "/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt"
        - name: PROMETHEUS_CLIENT_CERT_PATH
          value: ""
        - name: PROMETHEUS_CLIENT_KEY_PATH
          value: ""
        - name: PROMETHEUS_SERVER_NAME
          value: "thanos-querier.openshift-monitoring.svc"